set_property IOSTANDARD LVCMOS33 [get_ports {RX_DATA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_DATA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_DATA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_DATA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_DATA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_DATA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_DATA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_DATA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports RST]
set_property IOSTANDARD LVCMOS33 [get_ports RX_RDY]
set_property IOSTANDARD LVCMOS33 [get_ports RXD]
set_property PACKAGE_PIN H16 [get_ports CLK]
set_property PACKAGE_PIN D20 [get_ports RST]
set_property PACKAGE_PIN W13 [get_ports RX_RDY]
set_property PACKAGE_PIN Y16 [get_ports RXD]
set_property PACKAGE_PIN W16 [get_ports {RX_DATA[1]}]

set_property PACKAGE_PIN T10 [get_ports {RX_DATA[3]}]
set_property PACKAGE_PIN T11 [get_ports {RX_DATA[4]}]
set_property PACKAGE_PIN W14 [get_ports {RX_DATA[6]}]

set_property PACKAGE_PIN V12 [get_ports {RX_DATA[0]}]
set_property PACKAGE_PIN Y14 [get_ports {RX_DATA[5]}]
set_property PACKAGE_PIN V16 [get_ports {RX_DATA[2]}]
