# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/debug.xdc

# Block Designs: bd/my_SPI_RAM/my_SPI_RAM.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==my_SPI_RAM || ORIG_REF_NAME==my_SPI_RAM} -quiet] -quiet

# IP: bd/my_SPI_RAM/ip/my_SPI_RAM_processing_system7_0_0/my_SPI_RAM_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==my_SPI_RAM_processing_system7_0_0 || ORIG_REF_NAME==my_SPI_RAM_processing_system7_0_0} -quiet] -quiet

# IP: bd/my_SPI_RAM/ip/my_SPI_RAM_myip_slave_lite_v1_0_0_0/my_SPI_RAM_myip_slave_lite_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==my_SPI_RAM_myip_slave_lite_v1_0_0_0 || ORIG_REF_NAME==my_SPI_RAM_myip_slave_lite_v1_0_0_0} -quiet] -quiet

# IP: bd/my_SPI_RAM/ip/my_SPI_RAM_ps7_0_axi_periph_0/my_SPI_RAM_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==my_SPI_RAM_ps7_0_axi_periph_0 || ORIG_REF_NAME==my_SPI_RAM_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/my_SPI_RAM/ip/my_SPI_RAM_rst_ps7_0_100M_0/my_SPI_RAM_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==my_SPI_RAM_rst_ps7_0_100M_0 || ORIG_REF_NAME==my_SPI_RAM_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/my_SPI_RAM/ip/my_SPI_RAM_spi_master_0_0/my_SPI_RAM_spi_master_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==my_SPI_RAM_spi_master_0_0 || ORIG_REF_NAME==my_SPI_RAM_spi_master_0_0} -quiet] -quiet

# IP: bd/my_SPI_RAM/ip/my_SPI_RAM_spi_slave_0_0/my_SPI_RAM_spi_slave_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==my_SPI_RAM_spi_slave_0_0 || ORIG_REF_NAME==my_SPI_RAM_spi_slave_0_0} -quiet] -quiet

# IP: bd/my_SPI_RAM/ip/my_SPI_RAM_RAM_0_0/my_SPI_RAM_RAM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==my_SPI_RAM_RAM_0_0 || ORIG_REF_NAME==my_SPI_RAM_RAM_0_0} -quiet] -quiet

# IP: bd/my_SPI_RAM/ip/my_SPI_RAM_auto_pc_0/my_SPI_RAM_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==my_SPI_RAM_auto_pc_0 || ORIG_REF_NAME==my_SPI_RAM_auto_pc_0} -quiet] -quiet

# XDC: c:/Verilog-lab/my_SPI_RAM/my_SPI_RAM.gen/sources_1/bd/my_SPI_RAM/my_SPI_RAM_ooc.xdc
