
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list zynq_bd_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[0]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[1]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[2]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[3]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[4]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[5]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[6]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[7]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[8]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[9]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[10]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[11]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[12]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[13]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[14]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[15]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[16]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[17]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[18]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[19]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[20]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[21]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[22]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[23]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[24]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[25]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[26]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[27]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[28]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[29]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[30]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/slv_reg_sw[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[0]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[1]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[2]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[3]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[4]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[5]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[6]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[7]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[8]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[9]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[10]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[11]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[12]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[13]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[14]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[15]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[16]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[17]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[18]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[19]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[20]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[21]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[22]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[23]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[24]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[25]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[26]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[27]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[28]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[29]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[30]} {zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RDATA[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_ARESETN]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list zynq_bd_i/myip_slave_lite_v1_0_0/inst/S_AXI_RVALID]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
