# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Verilog-lab/Zynq_axi_7seg/Zynq_axi_7seg.srcs/sources_1/bd/Zynq_axi_7seg/ip/Zynq_axi_7seg_rst_ps7_0_100M_0/Zynq_axi_7seg_rst_ps7_0_100M_0.xci
# IP: The module: 'Zynq_axi_7seg_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Verilog-lab/Zynq_axi_7seg/Zynq_axi_7seg.gen/sources_1/bd/Zynq_axi_7seg/ip/Zynq_axi_7seg_rst_ps7_0_100M_0/Zynq_axi_7seg_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_axi_7seg_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Verilog-lab/Zynq_axi_7seg/Zynq_axi_7seg.gen/sources_1/bd/Zynq_axi_7seg/ip/Zynq_axi_7seg_rst_ps7_0_100M_0/Zynq_axi_7seg_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_axi_7seg_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Verilog-lab/Zynq_axi_7seg/Zynq_axi_7seg.gen/sources_1/bd/Zynq_axi_7seg/ip/Zynq_axi_7seg_rst_ps7_0_100M_0/Zynq_axi_7seg_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_axi_7seg_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Verilog-lab/Zynq_axi_7seg/Zynq_axi_7seg.srcs/sources_1/bd/Zynq_axi_7seg/ip/Zynq_axi_7seg_rst_ps7_0_100M_0/Zynq_axi_7seg_rst_ps7_0_100M_0.xci
# IP: The module: 'Zynq_axi_7seg_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Verilog-lab/Zynq_axi_7seg/Zynq_axi_7seg.gen/sources_1/bd/Zynq_axi_7seg/ip/Zynq_axi_7seg_rst_ps7_0_100M_0/Zynq_axi_7seg_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_axi_7seg_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Verilog-lab/Zynq_axi_7seg/Zynq_axi_7seg.gen/sources_1/bd/Zynq_axi_7seg/ip/Zynq_axi_7seg_rst_ps7_0_100M_0/Zynq_axi_7seg_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_axi_7seg_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Verilog-lab/Zynq_axi_7seg/Zynq_axi_7seg.gen/sources_1/bd/Zynq_axi_7seg/ip/Zynq_axi_7seg_rst_ps7_0_100M_0/Zynq_axi_7seg_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_axi_7seg_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
