# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/AXI_UART.xdc

# XDC: new/debug.xdc

# Block Designs: bd/AXI_UART/AXI_UART.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_UART || ORIG_REF_NAME==AXI_UART} -quiet] -quiet

# IP: bd/AXI_UART/ip/AXI_UART_processing_system7_0_1/AXI_UART_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_UART_processing_system7_0_1 || ORIG_REF_NAME==AXI_UART_processing_system7_0_1} -quiet] -quiet

# IP: bd/AXI_UART/ip/AXI_UART_myip_slave_lite_v1_0_0_1/AXI_UART_myip_slave_lite_v1_0_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_UART_myip_slave_lite_v1_0_0_1 || ORIG_REF_NAME==AXI_UART_myip_slave_lite_v1_0_0_1} -quiet] -quiet

# IP: bd/AXI_UART/ip/AXI_UART_ps7_0_axi_periph_1/AXI_UART_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_UART_ps7_0_axi_periph_1 || ORIG_REF_NAME==AXI_UART_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/AXI_UART/ip/AXI_UART_rst_ps7_0_50M_0/AXI_UART_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_UART_rst_ps7_0_50M_0 || ORIG_REF_NAME==AXI_UART_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/AXI_UART/ip/AXI_UART_my_uart_rx_0_1/AXI_UART_my_uart_rx_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_UART_my_uart_rx_0_1 || ORIG_REF_NAME==AXI_UART_my_uart_rx_0_1} -quiet] -quiet

# IP: bd/AXI_UART/ip/AXI_UART_my_uart_tx_0_1/AXI_UART_my_uart_tx_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_UART_my_uart_tx_0_1 || ORIG_REF_NAME==AXI_UART_my_uart_tx_0_1} -quiet] -quiet

# IP: bd/AXI_UART/ip/AXI_UART_auto_pc_0/AXI_UART_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_UART_auto_pc_0 || ORIG_REF_NAME==AXI_UART_auto_pc_0} -quiet] -quiet

# XDC: c:/Verilog-lab/AXI_UART/AXI_UART.gen/sources_1/bd/AXI_UART/AXI_UART_ooc.xdc
