# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Verilog-lab/my_SPI_RAM/my_SPI_RAM.srcs/sources_1/bd/my_SPI_RAM/ip/my_SPI_RAM_processing_system7_0_0/my_SPI_RAM_processing_system7_0_0.xci
# IP: The module: 'my_SPI_RAM_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Verilog-lab/my_SPI_RAM/my_SPI_RAM.gen/sources_1/bd/my_SPI_RAM/ip/my_SPI_RAM_processing_system7_0_0/my_SPI_RAM_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_SPI_RAM_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Verilog-lab/my_SPI_RAM/my_SPI_RAM.srcs/sources_1/bd/my_SPI_RAM/ip/my_SPI_RAM_processing_system7_0_0/my_SPI_RAM_processing_system7_0_0.xci
# IP: The module: 'my_SPI_RAM_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Verilog-lab/my_SPI_RAM/my_SPI_RAM.gen/sources_1/bd/my_SPI_RAM/ip/my_SPI_RAM_processing_system7_0_0/my_SPI_RAM_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_SPI_RAM_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
