set_property MARK_DEBUG true [get_nets RST_IBUF]
set_property MARK_DEBUG true [get_nets count_enable]
set_property MARK_DEBUG true [get_nets Alarm_Siren_OBUF]

set_property MARK_DEBUG true [get_nets {count[0]}]
set_property MARK_DEBUG true [get_nets {count[1]}]
set_property MARK_DEBUG true [get_nets {count[2]}]
set_property MARK_DEBUG true [get_nets {count[3]}]
set_property MARK_DEBUG true [get_nets {count[4]}]
set_property MARK_DEBUG true [get_nets {count[5]}]
set_property MARK_DEBUG true [get_nets {count[6]}]
set_property MARK_DEBUG true [get_nets {count[7]}]
set_property MARK_DEBUG true [get_nets {count[8]}]
set_property MARK_DEBUG true [get_nets {count[9]}]
set_property MARK_DEBUG true [get_nets {count[10]}]
set_property MARK_DEBUG true [get_nets {count[11]}]
set_property MARK_DEBUG true [get_nets {count[12]}]
set_property MARK_DEBUG true [get_nets {count[13]}]
set_property MARK_DEBUG true [get_nets {count[14]}]
set_property MARK_DEBUG true [get_nets {count[15]}]
set_property MARK_DEBUG true [get_nets {count[16]}]
set_property MARK_DEBUG true [get_nets {count[17]}]
set_property MARK_DEBUG true [get_nets {count[18]}]
set_property MARK_DEBUG true [get_nets {count[19]}]
set_property MARK_DEBUG true [get_nets {count[20]}]
set_property MARK_DEBUG true [get_nets {count[21]}]
set_property MARK_DEBUG true [get_nets {count[22]}]
set_property MARK_DEBUG true [get_nets {count[23]}]
set_property MARK_DEBUG true [get_nets {count[24]}]
set_property MARK_DEBUG true [get_nets {count[25]}]
set_property MARK_DEBUG true [get_nets {count[26]}]
set_property MARK_DEBUG true [get_nets {count[27]}]
set_property MARK_DEBUG true [get_nets {count[28]}]
set_property MARK_DEBUG true [get_nets {count[29]}]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list CLK_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 2 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {sensor[0]} {sensor[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 2 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {current_state[0]} {current_state[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 30 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {count[0]} {count[1]} {count[2]} {count[3]} {count[4]} {count[5]} {count[6]} {count[7]} {count[8]} {count[9]} {count[10]} {count[11]} {count[12]} {count[13]} {count[14]} {count[15]} {count[16]} {count[17]} {count[18]} {count[19]} {count[20]} {count[21]} {count[22]} {count[23]} {count[24]} {count[25]} {count[26]} {count[27]} {count[28]} {count[29]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list Alarm_Siren_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list count_enable]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list p_1_in]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list RST_IBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets CLK_IBUF_BUFG]
