domain_path: C:\Verilog-lab\zynq_axi_sw\zynq_axi_plat\export\zynq_axi_plat\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
