domain_path: c:\Verilog-lab\axi_dip2led_sw\axi_dip2led_basys_plat\export\axi_dip2led_basys_plat\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
