# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Verilog-lab/king/king.srcs/sources_1/bd/king_bd/ip/king_bd_auto_pc_0/king_bd_auto_pc_0.xci
# IP: The module: 'king_bd_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Verilog-lab/king/king.gen/sources_1/bd/king_bd/ip/king_bd_auto_pc_0/king_bd_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'king_bd_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Verilog-lab/king/king.srcs/sources_1/bd/king_bd/ip/king_bd_auto_pc_0/king_bd_auto_pc_0.xci
# IP: The module: 'king_bd_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Verilog-lab/king/king.gen/sources_1/bd/king_bd/ip/king_bd_auto_pc_0/king_bd_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'king_bd_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
