# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Verilog-lab/practice_zync_btns_leds/practice_zync_btns_leds.srcs/sources_1/bd/zync_basys/ip/zync_basys_rst_axi_gpio_dip_50M_0/zync_basys_rst_axi_gpio_dip_50M_0.xci
# IP: The module: 'zync_basys_rst_axi_gpio_dip_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Verilog-lab/practice_zync_btns_leds/practice_zync_btns_leds.gen/sources_1/bd/zync_basys/ip/zync_basys_rst_axi_gpio_dip_50M_0/zync_basys_rst_axi_gpio_dip_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zync_basys_rst_axi_gpio_dip_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Verilog-lab/practice_zync_btns_leds/practice_zync_btns_leds.gen/sources_1/bd/zync_basys/ip/zync_basys_rst_axi_gpio_dip_50M_0/zync_basys_rst_axi_gpio_dip_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zync_basys_rst_axi_gpio_dip_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Verilog-lab/practice_zync_btns_leds/practice_zync_btns_leds.gen/sources_1/bd/zync_basys/ip/zync_basys_rst_axi_gpio_dip_50M_0/zync_basys_rst_axi_gpio_dip_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zync_basys_rst_axi_gpio_dip_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Verilog-lab/practice_zync_btns_leds/practice_zync_btns_leds.srcs/sources_1/bd/zync_basys/ip/zync_basys_rst_axi_gpio_dip_50M_0/zync_basys_rst_axi_gpio_dip_50M_0.xci
# IP: The module: 'zync_basys_rst_axi_gpio_dip_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Verilog-lab/practice_zync_btns_leds/practice_zync_btns_leds.gen/sources_1/bd/zync_basys/ip/zync_basys_rst_axi_gpio_dip_50M_0/zync_basys_rst_axi_gpio_dip_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zync_basys_rst_axi_gpio_dip_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Verilog-lab/practice_zync_btns_leds/practice_zync_btns_leds.gen/sources_1/bd/zync_basys/ip/zync_basys_rst_axi_gpio_dip_50M_0/zync_basys_rst_axi_gpio_dip_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zync_basys_rst_axi_gpio_dip_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Verilog-lab/practice_zync_btns_leds/practice_zync_btns_leds.gen/sources_1/bd/zync_basys/ip/zync_basys_rst_axi_gpio_dip_50M_0/zync_basys_rst_axi_gpio_dip_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zync_basys_rst_axi_gpio_dip_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
