# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zync_basys/zync_basys.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zync_basys || ORIG_REF_NAME==zync_basys} -quiet] -quiet

# IP: bd/zync_basys/ip/zync_basys_processing_system7_0_0/zync_basys_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zync_basys_processing_system7_0_0 || ORIG_REF_NAME==zync_basys_processing_system7_0_0} -quiet] -quiet

# IP: bd/zync_basys/ip/zync_basys_axi_gpio_0_0/zync_basys_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zync_basys_axi_gpio_0_0 || ORIG_REF_NAME==zync_basys_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zync_basys/ip/zync_basys_xbar_0/zync_basys_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zync_basys_xbar_0 || ORIG_REF_NAME==zync_basys_xbar_0} -quiet] -quiet

# IP: bd/zync_basys/ip/zync_basys_axi_gpio_dip_axi_periph_0/zync_basys_axi_gpio_dip_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zync_basys_axi_gpio_dip_axi_periph_0 || ORIG_REF_NAME==zync_basys_axi_gpio_dip_axi_periph_0} -quiet] -quiet

# IP: bd/zync_basys/ip/zync_basys_rst_axi_gpio_dip_50M_0/zync_basys_rst_axi_gpio_dip_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zync_basys_rst_axi_gpio_dip_50M_0 || ORIG_REF_NAME==zync_basys_rst_axi_gpio_dip_50M_0} -quiet] -quiet

# IP: bd/zync_basys/ip/zync_basys_axi_gpio_1_0/zync_basys_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zync_basys_axi_gpio_1_0 || ORIG_REF_NAME==zync_basys_axi_gpio_1_0} -quiet] -quiet

# IP: bd/zync_basys/ip/zync_basys_auto_pc_0/zync_basys_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zync_basys_auto_pc_0 || ORIG_REF_NAME==zync_basys_auto_pc_0} -quiet] -quiet

# XDC: c:/Verilog-lab/practice_zync_btns_leds/practice_zync_btns_leds.gen/sources_1/bd/zync_basys/zync_basys_ooc.xdc
