domain_path: C:\Verilog-lab\my_SPI_RAM_sw\spi_ram_plat\export\spi_ram_plat\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2024.1\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
