# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/AXI_UART_CONST.xdc

# XDC: new/debug.xdc

# Block Designs: bd/AXI_UART_BD/AXI_UART_BD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_UART_BD || ORIG_REF_NAME==AXI_UART_BD} -quiet] -quiet

# IP: bd/AXI_UART_BD/ip/AXI_UART_BD_processing_system7_0_1/AXI_UART_BD_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_UART_BD_processing_system7_0_1 || ORIG_REF_NAME==AXI_UART_BD_processing_system7_0_1} -quiet] -quiet

# IP: bd/AXI_UART_BD/ip/AXI_UART_BD_myip_slave_lite_v1_0_0_0/AXI_UART_BD_myip_slave_lite_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_UART_BD_myip_slave_lite_v1_0_0_0 || ORIG_REF_NAME==AXI_UART_BD_myip_slave_lite_v1_0_0_0} -quiet] -quiet

# IP: bd/AXI_UART_BD/ip/AXI_UART_BD_ps7_0_axi_periph_0/AXI_UART_BD_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_UART_BD_ps7_0_axi_periph_0 || ORIG_REF_NAME==AXI_UART_BD_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/AXI_UART_BD/ip/AXI_UART_BD_rst_ps7_0_100M_0/AXI_UART_BD_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_UART_BD_rst_ps7_0_100M_0 || ORIG_REF_NAME==AXI_UART_BD_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/AXI_UART_BD/ip/AXI_UART_BD_my_uart_tx_0_0/AXI_UART_BD_my_uart_tx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_UART_BD_my_uart_tx_0_0 || ORIG_REF_NAME==AXI_UART_BD_my_uart_tx_0_0} -quiet] -quiet

# IP: bd/AXI_UART_BD/ip/AXI_UART_BD_my_uart_rx_0_0/AXI_UART_BD_my_uart_rx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_UART_BD_my_uart_rx_0_0 || ORIG_REF_NAME==AXI_UART_BD_my_uart_rx_0_0} -quiet] -quiet

# IP: bd/AXI_UART_BD/ip/AXI_UART_BD_auto_pc_0/AXI_UART_BD_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_UART_BD_auto_pc_0 || ORIG_REF_NAME==AXI_UART_BD_auto_pc_0} -quiet] -quiet

# XDC: c:/Verilog-lab/AXI_UART/AXI_UART.gen/sources_1/bd/AXI_UART_BD/AXI_UART_BD_ooc.xdc
