# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Zynq_axi_7seg.xdc

# Block Designs: bd/Zynq_axi_7seg/Zynq_axi_7seg.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_axi_7seg || ORIG_REF_NAME==Zynq_axi_7seg} -quiet] -quiet

# IP: bd/Zynq_axi_7seg/ip/Zynq_axi_7seg_processing_system7_0_0/Zynq_axi_7seg_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_axi_7seg_processing_system7_0_0 || ORIG_REF_NAME==Zynq_axi_7seg_processing_system7_0_0} -quiet] -quiet

# IP: bd/Zynq_axi_7seg/ip/Zynq_axi_7seg_myip_slave_lite_v1_0_0_0/Zynq_axi_7seg_myip_slave_lite_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_axi_7seg_myip_slave_lite_v1_0_0_0 || ORIG_REF_NAME==Zynq_axi_7seg_myip_slave_lite_v1_0_0_0} -quiet] -quiet

# IP: bd/Zynq_axi_7seg/ip/Zynq_axi_7seg_ps7_0_axi_periph_0/Zynq_axi_7seg_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_axi_7seg_ps7_0_axi_periph_0 || ORIG_REF_NAME==Zynq_axi_7seg_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Zynq_axi_7seg/ip/Zynq_axi_7seg_rst_ps7_0_100M_0/Zynq_axi_7seg_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_axi_7seg_rst_ps7_0_100M_0 || ORIG_REF_NAME==Zynq_axi_7seg_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Zynq_axi_7seg/ip/Zynq_axi_7seg_disp_mod_0_0/Zynq_axi_7seg_disp_mod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_axi_7seg_disp_mod_0_0 || ORIG_REF_NAME==Zynq_axi_7seg_disp_mod_0_0} -quiet] -quiet

# IP: bd/Zynq_axi_7seg/ip/Zynq_axi_7seg_tick_gen_100ms_0_0/Zynq_axi_7seg_tick_gen_100ms_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_axi_7seg_tick_gen_100ms_0_0 || ORIG_REF_NAME==Zynq_axi_7seg_tick_gen_100ms_0_0} -quiet] -quiet

# IP: bd/Zynq_axi_7seg/ip/Zynq_axi_7seg_xlslice_0_0/Zynq_axi_7seg_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_axi_7seg_xlslice_0_0 || ORIG_REF_NAME==Zynq_axi_7seg_xlslice_0_0} -quiet] -quiet

# IP: bd/Zynq_axi_7seg/ip/Zynq_axi_7seg_xlslice_1_0/Zynq_axi_7seg_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_axi_7seg_xlslice_1_0 || ORIG_REF_NAME==Zynq_axi_7seg_xlslice_1_0} -quiet] -quiet

# IP: bd/Zynq_axi_7seg/ip/Zynq_axi_7seg_auto_pc_0/Zynq_axi_7seg_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_axi_7seg_auto_pc_0 || ORIG_REF_NAME==Zynq_axi_7seg_auto_pc_0} -quiet] -quiet

# XDC: c:/Verilog-lab/Zynq_axi_7seg/Zynq_axi_7seg.gen/sources_1/bd/Zynq_axi_7seg/Zynq_axi_7seg_ooc.xdc
