# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Verilog-lab/AXI_UART/AXI_UART.srcs/sources_1/bd/AXI_UART/ip/AXI_UART_rst_ps7_0_50M_0/AXI_UART_rst_ps7_0_50M_0.xci
# IP: The module: 'AXI_UART_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Verilog-lab/AXI_UART/AXI_UART.gen/sources_1/bd/AXI_UART/ip/AXI_UART_rst_ps7_0_50M_0/AXI_UART_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_UART_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Verilog-lab/AXI_UART/AXI_UART.gen/sources_1/bd/AXI_UART/ip/AXI_UART_rst_ps7_0_50M_0/AXI_UART_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_UART_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Verilog-lab/AXI_UART/AXI_UART.gen/sources_1/bd/AXI_UART/ip/AXI_UART_rst_ps7_0_50M_0/AXI_UART_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_UART_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Verilog-lab/AXI_UART/AXI_UART.srcs/sources_1/bd/AXI_UART/ip/AXI_UART_rst_ps7_0_50M_0/AXI_UART_rst_ps7_0_50M_0.xci
# IP: The module: 'AXI_UART_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Verilog-lab/AXI_UART/AXI_UART.gen/sources_1/bd/AXI_UART/ip/AXI_UART_rst_ps7_0_50M_0/AXI_UART_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_UART_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Verilog-lab/AXI_UART/AXI_UART.gen/sources_1/bd/AXI_UART/ip/AXI_UART_rst_ps7_0_50M_0/AXI_UART_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_UART_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Verilog-lab/AXI_UART/AXI_UART.gen/sources_1/bd/AXI_UART/ip/AXI_UART_rst_ps7_0_50M_0/AXI_UART_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_UART_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
