# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/king.xdc

# Block Designs: bd/king_bd/king_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==king_bd || ORIG_REF_NAME==king_bd} -quiet] -quiet

# IP: bd/king_bd/ip/king_bd_processing_system7_0_0/king_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==king_bd_processing_system7_0_0 || ORIG_REF_NAME==king_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/king_bd/ip/king_bd_myip_slave_0_0/king_bd_myip_slave_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==king_bd_myip_slave_0_0 || ORIG_REF_NAME==king_bd_myip_slave_0_0} -quiet] -quiet

# IP: bd/king_bd/ip/king_bd_ps7_0_axi_periph_0/king_bd_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==king_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==king_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/king_bd/ip/king_bd_rst_ps7_0_100M_0/king_bd_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==king_bd_rst_ps7_0_100M_0 || ORIG_REF_NAME==king_bd_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/king_bd/ip/king_bd_my_uart_tx_0_0/king_bd_my_uart_tx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==king_bd_my_uart_tx_0_0 || ORIG_REF_NAME==king_bd_my_uart_tx_0_0} -quiet] -quiet

# IP: bd/king_bd/ip/king_bd_auto_pc_0/king_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==king_bd_auto_pc_0 || ORIG_REF_NAME==king_bd_auto_pc_0} -quiet] -quiet

# XDC: c:/Verilog-lab/king/king.gen/sources_1/bd/king_bd/king_bd_ooc.xdc
