set_property PACKAGE_PIN W14 [get_ports {SEG_H[6]}]
set_property PACKAGE_PIN Y14 [get_ports {SEG_H[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_H[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_H[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_H[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_H[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_H[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_H[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_H[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_L[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_L[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_L[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_L[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_L[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_L[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_L[0]}]
set_property PACKAGE_PIN T11 [get_ports {SEG_H[4]}]
set_property PACKAGE_PIN T10 [get_ports {SEG_H[3]}]
set_property PACKAGE_PIN V16 [get_ports {SEG_H[2]}]
set_property PACKAGE_PIN W16 [get_ports {SEG_H[1]}]
set_property PACKAGE_PIN V12 [get_ports {SEG_H[0]}]
set_property PACKAGE_PIN W13 [get_ports CA_H]
set_property IOSTANDARD LVCMOS33 [get_ports CA_H]
set_property IOSTANDARD LVCMOS33 [get_ports BTN_STOP]
set_property IOSTANDARD LVCMOS33 [get_ports BTN_DM]
set_property IOSTANDARD LVCMOS33 [get_ports CA_L]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property PACKAGE_PIN Y18 [get_ports {SEG_L[6]}]
set_property PACKAGE_PIN Y19 [get_ports {SEG_L[5]}]
set_property PACKAGE_PIN Y16 [get_ports {SEG_L[4]}]
set_property PACKAGE_PIN Y17 [get_ports {SEG_L[3]}]
set_property PACKAGE_PIN U18 [get_ports {SEG_L[2]}]
set_property PACKAGE_PIN U19 [get_ports {SEG_L[1]}]
set_property PACKAGE_PIN W18 [get_ports {SEG_L[0]}]
set_property PACKAGE_PIN W19 [get_ports CA_L]
set_property PACKAGE_PIN H16 [get_ports CLK]

set_property PACKAGE_PIN D19 [get_ports BTN_STOP]

set_property PACKAGE_PIN D20 [get_ports BTN_DM]

#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets BTN_STOP_IBUF]

set_property IOSTANDARD LVCMOS33 [get_ports BTN_DR]
set_property IOSTANDARD LVCMOS33 [get_ports BTN_SS]
set_property PACKAGE_PIN D19 [get_ports BTN_SS]
set_property PACKAGE_PIN D20 [get_ports BTN_DR]
set_property IOSTANDARD LVCMOS33 [get_ports LD0_G]
set_property IOSTANDARD LVCMOS33 [get_ports LD0_R]
set_property IOSTANDARD LVCMOS33 [get_ports LD1_G]
set_property IOSTANDARD LVCMOS33 [get_ports LD1_R]
set_property PACKAGE_PIN L14 [get_ports LD1_G]
set_property PACKAGE_PIN M15 [get_ports LD1_R]
set_property PACKAGE_PIN G17 [get_ports LD0_G]

set_property PACKAGE_PIN N15 [get_ports LD0_R]
