domain_path: c:\Verilog-lab\Zynq_axi_7seg_sw\axi_7seg_plat\export\axi_7seg_plat\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
